### ISSUE TITLE
`UndefVarError: _throw_invalid_usage not defined`

### ISSUE THREAD

**Issue by DilumAluthge** [KristofferC/LazilyInitializedFields.jl#13]
On `LazilyInitializedFields#master`, when I try to use the `@lazy` macro in an invalid way, instead of getting a useful error message that explains what I have done wrong, I get `UndefVarError: _throw_invalid_usage not defined`:

```julia
julia> @lazy struct MyStruct
           @lazy x::Int = 1
       end
ERROR: LoadError: UndefVarError: _throw_invalid_usage not defined
Stacktrace:
 [1] var"@lazy"(__source__::LineNumberNode, __module__::Module, expr::Any)
   @ LazilyInitializedFields ~/.julia/packages/LazilyInitializedFields/MKm9q/src/LazilyInitializedFields.jl:267
 [2] #macroexpand#55
   @ ./expr.jl:115 [inlined]
 [3] macroexpand
   @ ./expr.jl:114 [inlined]
 [4] lazy_struct(expr::Expr)
   @ LazilyInitializedFields ~/.julia/packages/LazilyInitializedFields/MKm9q/src/LazilyInitializedFields.jl:292
 [5] var"@lazy"(__source__::LineNumberNode, __module__::Module, expr::Any)
   @ LazilyInitializedFields ~/.julia/packages/LazilyInitializedFields/MKm9q/src/LazilyInitializedFields.jl:260
in expression starting at REPL[2]:1
```

It looks like `_throw_invalid_usage()` is being called on line 267 here: https://github.com/KristofferC/LazilyInitializedFields.jl/blob/bdf72861202599185b723b2df64a6602bbc3d91b/src/LazilyInitializedFields.jl#L264-L269

But I cannot find the definition of the `_throw_invalid_usage()` function anywhere in the package.

**Comment by KristofferC** [comment]
Seems that was missed. Should probably just be `error("invalid usage of @lazy macro")`
