### ISSUE TITLE
Initialize on access

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/LazilyInitializedFields.jl#8]
Could be nice to support adding syntax so that:

```jl
compute() = 2

@lazy struct Foo
    x::Int = 3
    @lazy field::Int = compute()
end

f = Foo()
f.field
```

would initialize `field` with the function `compute`.

**Comment by DilumAluthge** [comment]
This would be a really nice feature.

Would it make sense for the computation function to take the (partially-initialized) `f` as input?

So, e.g., something like this:

```julia
function compute_double end
@lazy struct LazyDoubler
    x::Int
    @lazy double_of_x::Int = compute_double
end
LazyDoubler(x::Int) = LazyDoubler(x, uninit)
compute_double(foo::LazyDoubler) = foo.x + foo.x

bar = LazyDoubler(3)
bar.double_of_x # this will be computed on-demand, and the result will be 6
```

**Comment by ameligrana** [comment]
I wonder if this is not better:

```julia
@lazy @kwdef struct Foo
    x::Int = 3
    @lazy field::Int = compute()
end
```

I also think that indeed adding `@kwdef` somewhere inside the macro could solve the issue maybe

**Comment by ameligrana** [comment]
actually the `@kwdef` macro requires keywords argument for the unitialized fields so it is not the same feature requested here, but I think that making `@lazy` compatible with `@kwdef` is nonetheless a good feature

**Comment by BambOoxX** [comment]
I am not sure if this is related, but would it make sense to support `get(<lazystruct>,:<lazyprop>,<lazydefault>)` when `isinit(<lazystruct>,:<lazyprop>) == true` returns `<lazyprop>` when `false` returns `<lazydefault>` ?
